### ISSUE TITLE
About Sprint & Rotate Training

### ISSUE THREAD

**Issue by Yorkgithubaccount** [m-abr/FCPCodebase#10]
The reward of Sprint & Rotate training includes the 2-dimensional vector speed_2d, while the reward for reinforcement learning should be a scalar. How to convert this vector to a scalar for training?  And how speed_2d is defined？Thx

**Comment by m-abr** [comment]
I try to follow a convention that distinguishes between speed and velocity. When I refer to speed, I'm specifically talking about the scalar quantity, while velocity denotes the vector, encompassing both direction and magnitude. I understand how the term 'speed_2d' might be ambiguous. To clarify, 'speed_2d' represents the scalar speed measured in the xy plane, excluding any changes in the z-axis. Essentially, 'speed_2d' is the magnitude of the 2D velocity vector (vx, vy).

**Comment by Yorkgithubaccount** [comment]
I got it, Thx
