### ISSUE TITLE
Is there a script for automatic play, and what should I do if I want to play multiple matches against other teams?

### ISSUE THREAD

**Issue by chance20210722** [m-abr/FCPCodebase#15]

**Comment by chance20210722** [comment]
We used to have an auto-match script, but it was a \"UT\" based code, and now we've switched to your code, and we don't know how to do that at the moment.

**Comment by m-abr** [comment]
Unfortunately this codebase doesn't have any form of auto-match script. Maybe you can create one or adapt the UT script?

**Comment by chance20210722** [comment]
> script

OK,thanks
