### ISSUE TITLE
Run_Utils error

### ISSUE THREAD

**Issue by Aike2071** [m-abr/FCPCodebase#4]
hello,I did all the setup steps,but when I run the code python3 Run_Utils.py,there is an error :Traceback (most recent call last):
  File "/home/aike/FCPCodebase-main/Run_Utils.py", line 93, in <module>
    main()
  File "/home/aike/FCPCodebase-main/Run_Utils.py", line 3, in main
    from scripts.commons.Script import Script
ModuleNotFoundError: No module named 'scripts.commons'

and I absolutely downloaded scripts module yet fail to fina a module named scripts.commons.How should I solve the error?

**Comment by m-abr** [comment]
First, check it the Script.py file exists in the following directory:
```
/FCPCodebase-main
├── scripts
│  └── commons
│     └── Script.py
└── Run_Utils.py
```

Then run:
```
cd /home/aike/FCPCodebase-main
python3 Run_Utils.py
```

If it fails: 
-what version of Python are you using?
-what Operative System / version?

**Comment by Aike2071** [comment]
I'm using python3.7 in Ubuntu,and the file directory  is the same as that on github code page shows.Should I upgrade my python to a certain version?

**Comment by m-abr** [comment]
The Python version does not seem to be the problem.

Please check the current permissions of the relevant files and folders:
```
cd /home/aike/FCPCodebase-main
ls -l scripts/ scripts/commons/ .
```
If needed, fix with:
```
chmod -R 755 .
```
The error could be due to incorrect folder permissions.
However, I'm uncertain about what could cause those unusual permissions.

**Comment by Aike2071** [comment]
Thanks a lot for your help.Problem was solved by re-downloading ZIP file instead of using git clone XD.
