### ISSUE TITLE
how to create a new motion

### ISSUE THREAD

**Issue by Dionysus7777777** [m-abr/FCPCodebase#6]
What is the purpose of the scripts file? If I have defined a new action, such as Quick_Kick which is at the same level as Basic_Kick, where else do I need to define this action? Do I need to rewrite a Kick script in the scripts directory?

**Comment by m-abr** [comment]
Basic_Kick is a custom behavior.
To create a custom behavior, read Section 5.2 of the [documentation](https://docs.google.com/document/d/1aJhwK2iJtU-ri_2JOB8iYvxzbPskJ8kbk_4rb3IK3yc/edit).

After creating the behavior, you have to add your new class to the declaration of behaviors in **/behaviors/behavior.py**

Line 46 of **/behaviors/behavior.py**:
<pre>
from behaviors.custom.Basic_Kick.Basic_Kick import Basic_Kick
from behaviors.custom.Dribble.Dribble import Dribble
from behaviors.custom.Fall.Fall import Fall
from behaviors.custom.Get_Up.Get_Up import Get_Up
from behaviors.custom.Step.Step import Step
from behaviors.custom.Walk.Walk import Walk
<b>from behaviors.custom.Quick_Kick.Quick_Kick import Quick_Kick<b>      # import your new class
classes = [Basic_Kick,Dribble,Fall,Get_Up,Step,Walk,<b>Quick_Kick<b>]    # add it to this list
<pre>

**Comment by Dionysus7777777** [comment]
thanks
