### ISSUE TITLE
Influence of the number of keyframes on the behavioral effect

### ISSUE THREAD

**Issue by Duanyy0813** [m-abr/FCPCodebase#8]
We tried to use CMAES algorithm to optimize the robot Kick Motion behavior, but the final effect is not very ideal. We guessed that the number of keyframes was limiting the final effect of the behavior, and we tried to change it, but it didn't work very well. Does the number of keyframes have a limiting effect on the behavioral effect? If so, how can we change it to achieve better results? Here is what we have achieved so far using the CMAES algorithm.
![R4_KICK_TEST](https://github.com/m-abr/FCPCodebase/assets/106674055/e5644e36-1c27-4287-83d0-2405a887091e)

**Comment by m-abr** [comment]
If your goal is to maximize the distance the ball travels when kicked, the primary flaw in the current Kick Motion is its preparation stage, where the robot swings its kicking leg backward. This stage needs to be extended to allow for a longer swing, which can result in more powerful kicks. As you suggested, the number of keyframes plays a role in the final outcome, but it's difficult to predict how adjusting this number will impact the result.

Alternatively, there's the option of learning from scratch, as I mentioned in Issue #5 (see [this answer](https://github.com/m-abr/FCPCodebase/issues/5#issuecomment-1996125371)). Please take a look.
